import java.sql.*;
import javax.swing.JOptionPane;

/**GUI que permite crear una entrada al historial médico del paciente
 *
 * @author a-carrasquillo
 * @author arivesan
 */
public class Create_Medical_History extends javax.swing.JFrame {
    //data fields
    private String id_medico;
    private String id_p;
    // constantes relacionadas a la base de datos
    private final String YourPassWord = "YourPassWord";
    private final String DBUSER = "dbuser";
    
    /**Constructor por defecto
     * Crea un nuevo formulario Create_Medical_History
     */    
    public Create_Medical_History() {
        initComponents();
        this.setLocationRelativeTo(null);
        // elimina el mensaje de error por defecto
        error.setText("");
    }
    
    /**Constructor especial 1
     * 
     * @param id_medico - número de identificación del médico
     */
    public Create_Medical_History(String id_medico) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id_medico = id_medico;
        // elimina el mensaje de error por defecto
        error.setText("");
    }
    
    /**Constructor especial 2
     * 
     * @param id_medico - número de identificación del médico
     * @param id_p - número de identificación del paciente
     */
    public Create_Medical_History(String id_medico, String id_p) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id_medico = id_medico;
        this.id_p = id_p;
        id_paciente.setText(id_p);
        // elimina el mensaje de error por defecto
        error.setText("");
    }
    
    /**Método que nos permite recuperar el id del médico
     * 
     * @return cadena de caracteres que representa el id del médico
     */
    public String getIdMedico()
    {
        return id_medico;
    }
    
    /**Método que nos permite modificar el id del médico
     * 
     * @param id_medico - número de identificación del médico
     */
    public void setIdMedico(String id_medico)
    {
        this.id_medico = id_medico;
    }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        height = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        weight = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        allergies = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_paciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_exam_fisico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        problema_actual = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cond_salud = new javax.swing.JTextArea();
        go_back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrada de Historial Médico");

        height.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        height.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Estatura:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Peso:");

        weight.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        weight.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Alergias:");

        allergies.setColumns(20);
        allergies.setRows(5);
        jScrollPane3.setViewportView(allergies);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Centímetros");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Libras");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("ID Paciente:");

        id_paciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(height, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)))
                    .addComponent(id_paciente)
                    .addComponent(jScrollPane3))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Información General", jPanel1);

        result_exam_fisico.setColumns(20);
        result_exam_fisico.setRows(5);
        jScrollPane1.setViewportView(result_exam_fisico);

        jTabbedPane1.addTab("Resultado Examen Físico", jScrollPane1);

        problema_actual.setColumns(20);
        problema_actual.setRows(5);
        jScrollPane2.setViewportView(problema_actual);

        jTabbedPane1.addTab("Problema Actual", jScrollPane2);

        cond_salud.setColumns(20);
        cond_salud.setRows(5);
        jScrollPane4.setViewportView(cond_salud);

        jTabbedPane1.addTab("Condición Salud", jScrollPane4);

        go_back.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        go_back.setText("Volver Atrás");
        go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_backActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        submit.setText("Someter");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setText("Mensaje de Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(go_back, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(go_back)
                    .addComponent(submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_backActionPerformed
        // crea una instancia del menú principal del médico
        DoctorUserForm doctor = new DoctorUserForm(id_medico, id_p); 
        // cerrar el GUI actual
        this.dispose();
         // hacer visible el nuevo GUI
        doctor.setVisible(true);
    }//GEN-LAST:event_go_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // elimina el mensaje de error
        error.setText(" ");
        
        // recuperar los valores de los campos
        String estatura = String.valueOf(height.getValue());
        String peso = String.valueOf(weight.getValue());
        String alergias = allergies.getText();
        String resultadoExamFisico = result_exam_fisico.getText();
        String problemaActual = problema_actual.getText();
        String condSalud = cond_salud.getText();
        
        // verificar si dejo algo en blanco
        if(alergias.isEmpty()||resultadoExamFisico.isEmpty()||problemaActual.isEmpty()||condSalud.isEmpty()||peso.equals("0")||estatura.equals("0"))
        {
            error.setText("Favor de no dejar espacios en blanco!");
        }
        else
        {
            Connection coneccion = null;
            PreparedStatement p_statement = null;
            final int ID_HISTORIAL = 0;
            try
                {
                    coneccion = DriverManager.getConnection("jdbc:mysql://localhost:3306/MedExpress?autoReconnect=true&useSSL=false",DBUSER,YourPassWord);
                    String query = "insert into Historial_Medico values("+ID_HISTORIAL+",'"+id_medico+"',"+estatura+", '"+ resultadoExamFisico+"', '"+ problemaActual+"'," + "Curdate()" + ", " + peso + ", '" + condSalud + "', '" + alergias + "', '"+ id_p + "')";
                    p_statement = coneccion.prepareStatement(query);
                    
                    // realizar la inserción
                    if(p_statement.executeUpdate()>=0)
                    {
                        JOptionPane.showMessageDialog(null, "Información Transferida Correctamente.");
                        // instanciar el menú principal del doctor
                        DoctorUserForm doctor = new DoctorUserForm(id_medico, id_p); 
                        // cerrar el GUI actual
                        this.dispose();
                        // hacer visible el GUI nuevo
                        doctor.setVisible(true);
                    }
                    
                    try{p_statement.close();}catch(SQLException e) {/*blank intentionally*/}

                }catch(SQLException e)
                {
                    /*blank intentionally*/
                 }
                finally
                {
                    try{
                        if(p_statement != null)
                            p_statement.close();
                        if(coneccion != null)
                            coneccion.close();
                    } catch(SQLException e) 
                    {
                        /*blank intentionally*/
                    }
                }
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Medical_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Medical_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Medical_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Medical_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Medical_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea allergies;
    private javax.swing.JTextArea cond_salud;
    private javax.swing.JLabel error;
    private javax.swing.JButton go_back;
    private javax.swing.JSpinner height;
    private javax.swing.JTextField id_paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea problema_actual;
    private javax.swing.JTextArea result_exam_fisico;
    private javax.swing.JButton submit;
    private javax.swing.JSpinner weight;
    // End of variables declaration//GEN-END:variables
}
