import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**GUI que nos permite modificar la contraseña de un paciente
 *
 * @author a-carrasquillo
 * @author arivesan
 */
public class ForgotPwdPacient extends javax.swing.JFrame {
    //data field
    private String id_paciente;
    // constantes relacionadas a la base de datos
    private final String YOURPASSWORD = "YourPassWord";
    private final String DBUSER = "dbuser";
    
   /**Constructor por defecto
     * Crea un nuevo formulario ForgotPwdPacient
     */
    public ForgotPwdPacient() {
        initComponents();
        this.setLocationRelativeTo(null);
        // elimina el mensaje de error por defecto
        error.setText("");
    }
    
    /**Constructor especial
     * 
     * @param id_paciente - número de identificación del paciente
     */
    public ForgotPwdPacient(String id_paciente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id_paciente = id_paciente;
        // elimina el mensaje de error por defecto
        error.setText("");
    }
    
    /**Método que nos permite recuperar el id del paciente
     * 
     * @return cadena de caracteres que representa el id del paciente
     */
    public String getIdPaciente()
    {
        return id_paciente;
    }
    
    /**Método que nos permite modificar el id del paciente
     * 
     * @param id_paciente - número de identificación del paciente
     */
    public void setIdPeciente(String id_paciente)
    {
        this.id_paciente = id_paciente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ss = new javax.swing.JTextField();
        zip_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        pass_conf = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambio de Contraseña");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Últimos 4 dígitos del SS:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Código Postal:");

        ss.setColumns(4);
        ss.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        zip_code.setColumns(5);
        zip_code.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nueva Contraseña:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Confirmar Contraseña:");

        pass.setColumns(20);
        pass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pass.setText("123456");
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        pass_conf.setColumns(20);
        pass_conf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pass_conf.setText("123456");
        pass_conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass_confMouseClicked(evt);
            }
        });
        pass_conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_confActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        submit.setText("Realizar Cambio");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setText("Mensaje de Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_conf, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(zip_code)
                    .addComponent(ss))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(submit)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zip_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pass_conf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // borrar el mensaje de error
        error.setText("");
        
        // recuperar los valores de los campos
        String zip = zip_code.getText();
        String seguroS = ss.getText();
        String password = String.valueOf(pass.getPassword());
        String pass_ver = String.valueOf(pass_conf.getPassword());
         
        Connection coneccion = null;
        // verificar que la contraseña sea igual al de confirmación y que no esté vacía
        if (!password.isEmpty()&&password.equals(pass_ver))
        {//las contraseñas coinciden
            // verificar que la información requerida este cumplimentada
            if(id_paciente.isEmpty()||zip.isEmpty()||seguroS.isEmpty())
            {
                error.setText("¡Favor de no dejar espacios en blanco!");
            }
            else
            {
                try
                {
                    coneccion = DriverManager.getConnection("jdbc:mysql://localhost:3306/MedExpress?autoReconnect=true&useSSL=false",DBUSER,YOURPASSWORD);
                    // query para obtener el seguro social y el código postal del paciente
                    String query = "select SS, Zip_Code from MedExpress.Pacientes where ID_Paciente ='" + id_paciente +"'";
                    Statement statement = coneccion.createStatement();
                    ResultSet result = statement.executeQuery(query);
                    // Determinar si hubo un resultado
                    while(result.next())
                    {
                        // extraer el resultado
                        String seguroSocialDB = result.getString("SS");
                        String zipCodeDB = result.getString("Zip_Code");
                        
                        // verificar que el seguro social y el código postal obtenidos del usuario coincidan con el de la base de datos
                        if(seguroSocialDB.equals(seguroS)&&zipCodeDB.equals(zip))
                        {//el usuario introduce correctamente su información de recuperación
                            JOptionPane.showMessageDialog(null, "Su información ha sido verificada correctamente. Comenzando cambio de contraseña...");
                            
                            Connection coneccion2 = null;
                            PreparedStatement p_statement2 = null;
                            try
                            {
                                coneccion2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/MedExpress?autoReconnect=true&useSSL=false",DBUSER,YOURPASSWORD);
                                // query para actualizar la contraseña
                                String query2 = "update MedExpress.Pacientes set Pwd = '" + password+"' where Id_Paciente = '" + id_paciente +"' ";
                                p_statement2 = coneccion2.prepareStatement(query2);
                                
                                // actualizar la contraseña
                                if(p_statement2.executeUpdate() > 0)
                                {
                                    JOptionPane.showMessageDialog(null, "¡Actualización exitosa!" );
                                    // cerrar el GUI actual
                                    this.dispose();
                                    // crear una instancia de la GUI de inicio de sesión de los pacientes
                                    Login_Patient paciente = new Login_Patient();
                                    // hacer visible el nuevo GUI
                                    paciente.setVisible(true);
                                }
                            }catch(SQLException e)
                            {
                                /*blank intentionally*/
                            }
                            finally
                            {
                                try
                                {
                                    if(p_statement2 != null)
                                        p_statement2.close();
                                } catch(SQLException e) 
                                {
                                    /*blank intentionally*/
                                }
                                try{
                                    if(coneccion2 != null)
                                        coneccion2.close();
                                } catch(SQLException e)
                                {
                                    /*blank intentionally*/
                                }
                            }                                            
                        } 
                    }
                    try{result.close();}catch(SQLException e){ /*blank intentionally*/}
                    try{statement.close();}catch(SQLException e) {/*blank intentionally*/}
                }catch(SQLException e)
                {
                     /*blank intentionally*/
                }
                finally
                {
                    try
                    {
                        if(coneccion != null)
                            coneccion.close();
                    } catch(SQLException e)
                    {
                        /*blank intentionally*/
                    }
                }
            }
        }
        else
            error.setText("¡Las contraseñas no coinciden!");
    }//GEN-LAST:event_submitActionPerformed

    private void pass_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_confActionPerformed
        // eliminar la información por defecto
        error.setText("");
        // extraer la contraseña y su verificación
        String password = String.valueOf(pass.getPassword());
        String pass_ver = String.valueOf(pass_conf.getPassword());
        // evaluar si la contraseña la escribió bien en los dos encasillados
        if(!pass_ver.equals(password))
            error.setText("¡Las contraseñas no coinciden!");
    }//GEN-LAST:event_pass_confActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // eliminar la información por defecto del encasillado
        error.setText("");
    }//GEN-LAST:event_passActionPerformed

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        // eliminar la información por defecto del encasillado
        pass.setText("");
    }//GEN-LAST:event_passMouseClicked

    private void pass_confMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_confMouseClicked
        // eliminar la información por defecto del encasillado
        pass_conf.setText("");
    }//GEN-LAST:event_pass_confMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPwdPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPwdPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPwdPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPwdPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPwdPacient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass_conf;
    private javax.swing.JTextField ss;
    private javax.swing.JButton submit;
    private javax.swing.JTextField zip_code;
    // End of variables declaration//GEN-END:variables
}
