import javax.swing.JOptionPane;

/** GUI utilizado para mostrar los resultados del prediagnóstico
 *
 * @author a-carrasquillo
 */
public class Resultados extends javax.swing.JFrame {
    // data fields
    private String id_paciente;
    private Patient_Info info;
    
    /**Constructor por defecto
     * Crea un nuevo formulario Resultados
     */
    public Resultados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**Constructor especial 
     * 
     * @param info - objeto con la información del paciente
     * @param id_paciente - número de identificación del paciente
     */
    public Resultados(Patient_Info info, String id_paciente) {
        initComponents();
        this.setLocationRelativeTo(null);
        // asignar los argumentos a los data fields
        this.info = new Patient_Info(info);
        this.id_paciente = id_paciente;
    }
    
    /**Método que nos permite modificar el prediagnóstico del paciente
     * 
     * @param prediag - prediagnóstico del paciente
     */
    public void setInfoPrediag(String prediag) {
        info.setPreDiag(prediag);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTable();
        send_info = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultados");

        resultados.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Prediagnóstico", "Probabilidad", "Clasificación", "Donde debe asistir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultados);
        if (resultados.getColumnModel().getColumnCount() > 0) {
            resultados.getColumnModel().getColumn(0).setHeaderValue("Prediagnóstico");
            resultados.getColumnModel().getColumn(1).setHeaderValue("Probabilidad");
            resultados.getColumnModel().getColumn(2).setHeaderValue("Clasificación");
            resultados.getColumnModel().getColumn(3).setHeaderValue("Donde debe asistir");
        }

        send_info.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        send_info.setText("Enviar Información a una Facilidad Médica");
        send_info.setMaximumSize(new java.awt.Dimension(69, 31));
        send_info.setMinimumSize(new java.awt.Dimension(69, 31));
        send_info.setPreferredSize(new java.awt.Dimension(69, 31));
        send_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_infoActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        close.setText("Cerrar");
        close.setMaximumSize(new java.awt.Dimension(69, 31));
        close.setMinimumSize(new java.awt.Dimension(69, 31));
        close.setPreferredSize(new java.awt.Dimension(69, 31));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(send_info, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        send_info.getAccessibleContext().setAccessibleName("close");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_infoActionPerformed
        // cerrar el GUI actual
        this.dispose();
        // crear instancia del GUI que nos permite buscar una facilidad médica
        Search_Medical_Facility facilidad = new Search_Medical_Facility(id_paciente, info);
        // hacer visible el nuevo GUI
        facilidad.setVisible(true);
    }//GEN-LAST:event_send_infoActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // Mensaje de despedida
        JOptionPane.showMessageDialog(null, "¡Gracias por utilizar nuestros servicios!"); 
        // cerrar el GUI actual
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable resultados;
    protected javax.swing.JButton send_info;
    // End of variables declaration//GEN-END:variables
}
